name: codr
description: An app made by Akhil Ramidi

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Authorization
  google_sign_in: "^4.5.1"
  flutter_facebook_auth: ^2.0.0+1
  # sign_in_with_apple: ^2.5.2
  github_sign_in: ^0.0.1

  # Firebase
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.4+1
  firebase_analytics: ^6.2.0
  firebase_crashlytics: ^0.2.3
  firebase_performance: ^0.4.2

  # Miscellaneous
  rxdart: ^0.24.1
  font_awesome_flutter: ^8.10.0
  flutter_chips_input: ^1.9.5
  crypto: ^2.1.5
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/Muli.ttf
        - asset: assets/Muli-Bold.ttf
          weight: 700
        - asset: assets/Muli-SemiBold.ttf
          weight: 600
    - family: AdobeClean
      fonts:
        - asset: assets/AdobeClean-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/NotoSans-Bold.ttf
  assets:
    - assets/Mediamodifier-Design-Template.png
    - assets/logo.png

  uses-material-design: true
